name: Go Build

on: 
  push:
    branches:
      - first-iteration
    tags:
      - 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Go
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'
    
      - name: List files
        run: ls -R
      
      - name: Go Dependencies
        run: go mod tidy
        
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
    
  publish: 
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 
    
      - name: Log in to Docker Hub  
        uses: docker/login-action@v2  
        with:  
            username: ${{ secrets.FIRST_SECRET }}  
            password: ${{ secrets.SECOND_SECRET }} 

      - name: Build and push Docker image  
        run: |
          docker build -t 12-sprint:{{ github.ref_name }} .
          docker push 12-sprint:{{ github.ref_name }}