name: Go Build

on: 
  push:
    branches:
      - pr
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Go
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
    
      - name: List files
        run: ls -R
      
      - name: Go Dependencies
        run: go mod tidy
        
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
    